apiVersion: v1
kind: Pod
metadata:
  name: api
  labels:
    app: api
spec:
  containers:
    - name: api
      image: jtedjosoesilo/be-prod
      ports:
        - containerPort: 8080
          name: "api"