version: '3.9'

services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: ./api
      target: dev
    volumes:
      - './api:/app/api'
    environment:
      - PORT=8080
    ports:
      - ${APP_SERVER_PORT}:8080
    
  ui:
    container_name: ui
    build: ./ui-depr
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=3000
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:3000
    volumes:
      - './ui-depr:/app/ui'
      - '/app/ui/node_modules'
    links:
      - api