apiVersion: v1
kind: Pod
metadata:
  name: ui
  labels:
    app: ui
spec:
  containers:
    - name: ui
      image: jtedjosoesilo/fe-prod
      ports:
        - containerPort: 3000
          name: "ui"